In [24]:
#Import necessary libraries
import os
import pandas as pd
import json

In [25]:
# #Set the working directory
# os.chdir("E:/Users/pc/Downloads/Enterprise Data Sciencfe Project")

In [26]:
#Import dataset(s)
train_revenue = pd.read_csv("train.csv")
test_revenue = pd.read_csv("test.csv")

C:\Users\pc\AppData\Local\Temp\ipykernel_21380\18681393.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  train_revenue = pd.read_csv("train.csv")
C:\Users\pc\AppData\Local\Temp\ipykernel_21380\18681393.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  test_revenue = pd.read_csv("test.csv")

In [27]:
dict_columns = ['geoNetwork', 'device', 'totals', 'trafficSource']

# For each such column, convert the string representation of dictionary to actual dictionary
# then normalize and concatenate with the original DataFrame
for column in dict_columns:
    # Convert the stringified dictionary to actual dictionary
    train_revenue[column] = train_revenue[column].apply(json.loads)
    
    # Flatten the dictionary and convert to a DataFrame
    column_df = pd.json_normalize(train_revenue[column])
    
    # Concatenate the new DataFrame to the original DataFrame
    train_revenue = pd.concat([train_revenue, column_df], axis=1)

    # Drop the original column that contained the stringified dictionary
    train_revenue.drop(column, axis=1, inplace=True)

for column in dict_columns:
    # Convert the stringified dictionary to actual dictionary
    test_revenue[column] = test_revenue[column].apply(json.loads)
    
    # Flatten the dictionary and convert to a DataFrame
    column_df = pd.json_normalize(test_revenue[column])
    
    # Concatenate the new DataFrame to the original DataFrame
    test_revenue = pd.concat([test_revenue, column_df], axis=1)

    # Drop the original column that contained the stringified dictionary
    test_revenue.drop(column, axis=1, inplace=True)

In [28]:
#Viewing first 5 rows of the training dataset
train_revenue.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,continent,subContinent,...,adwordsClickInfo.criteriaParameters,isTrueDirect,referralPath,adwordsClickInfo.page,adwordsClickInfo.slot,adwordsClickInfo.gclId,adwordsClickInfo.adNetworkType,adwordsClickInfo.isVideoAd,adContent,campaignCode
0,Organic Search,20160902,1131660440785968503,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Asia,Western Asia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,20160902,377306020877927890,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Oceania,Australasia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20160902,3895546263509774583,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Europe,Southern Europe,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,20160902,4763447161404445595,4763447161404445595_1472881213,Not Socially Engaged,1472881213,1,1472881213,Asia,Southeast Asia,...,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20160902,27294437909732085,27294437909732085_1472822600,Not Socially Engaged,1472822600,2,1472822600,Europe,Northern Europe,...,not available in demo dataset,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
#Viewing first 5 rows of the testing dataset
test_revenue.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,continent,subContinent,...,keyword,isTrueDirect,adwordsClickInfo.criteriaParameters,adwordsClickInfo.page,adwordsClickInfo.slot,adwordsClickInfo.gclId,adwordsClickInfo.adNetworkType,adwordsClickInfo.isVideoAd,referralPath,adContent
0,Organic Search,20171016,6167871330617112363,6167871330617112363_1508151024,Not Socially Engaged,1508151024,2,1508151024,Asia,Southeast Asia,...,(not provided),True,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,20171016,0643697640977915618,0643697640977915618_1508175522,Not Socially Engaged,1508175522,1,1508175522,Europe,Southern Europe,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20171016,6059383810968229466,6059383810968229466_1508143220,Not Socially Engaged,1508143220,1,1508143220,Europe,Western Europe,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,20171016,2376720078563423631,2376720078563423631_1508193530,Not Socially Engaged,1508193530,1,1508193530,Americas,Northern America,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20171016,2314544520795440038,2314544520795440038_1508217442,Not Socially Engaged,1508217442,1,1508217442,Americas,Northern America,...,(not provided),NaN,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# #Exporting the modified train dataset to csv
# train_revenue.to_csv("E:/train_dejsonified.csv",index=False)

# #Exporting the modified test dataset to csv
# test_revenue.to_csv("E:/test_dejsonified.csv",index=False)